const routes = {
    home: '/',
    travel: '/travel',
    advertise: '/advertise',
    article: '/advertise/:slug',
    news: '/news',
    about: '/about',
    contact: '/contact',
    search: '/search',
    tour: '/tour/:slug',
    book: '/book/:slug',
    payment: '/payment/:slug',
    confirm: '/confirm/:slug',
    login: '/login',
    register: '/register',
    cart: '/cart',
    accinfo: '/accinfo',
    bh: '/bh',
    notfound: '*',
    // admin
    adminDashboard: '/admin/dashboard',
    adminAccounts: '/admin/accounts',
    adminTours: '/admin/tours',
    adminTourUpdate: '/admin/tour/:slug',
    adminTourCreate: '/admin/tour/create',
    adminTourSchedules: '/admin/tourschedules',
    adminTourScheduleUpdate: '/admin/tourschedule/:slug',
};

export default routes;
