export {
    BookingHistoryTable,
    AdminAccoutTable,
    BookingDashboardTable,
    AdminTourTable,
    AdminTourScheduleTable,
    AdminTourDetailsTable,
    AdminArticleTable,
    AdminFAQTable,
    AdminContactEmailTable,
    AdminNewsTable,
    AdminReportRevenueTable,
    AdminReportTouristTable,
    AdminTourGuideTable,
} from './Table';
